// button
export const accept_icon = require('./button/accept_icon.png')
export const apple_icon = require('./button/apple_icon.png')
export const back_btn = require('./button/back_btn.png')
export const caution_icon = require('./button/caution_icon.png')
export const caution_icon_gray = require('./button/caution_icon_gray.png')
export const google_icon = require('./button/google_icon.png')
export const kakao_icon = require('./button/kakao_icon.png')
export const next_btn = require('./button/next_btn.png')
export const refuse_icon = require('./button/refuse_icon.png')
// emoji
export const emoji_01 = require('./emoji/emoji_01.png')
export const emoji_02 = require('./emoji/emoji_02.png')
// step
export const step_icon_default = require('./step/step_icon_default.png')
export const step_icon_end = require('./step/step_icon_end.png')
export const step_icon_now = require('./step/step_icon_now.png')
// common
export const adaptive_icon = require('./common/adaptive_icon.png')
export const back_button = require('./common/back_button.png')
export const edit = require('./common/edit.png')
export const favicon = require('./common/favicon.png')
export const ic_alert = require('./common/ic_alert.png')
export const ic_friends = require('./common/ic_friends.png')
export const ic_inquiry = require('./common/ic_inquiry.png')
export const ic_leave = require('./common/ic_leave.png')
export const ic_logout = require('./common/ic_logout.png')
export const ic_setting = require('./common/ic_setting.png')
export const ic_terms = require('./common/ic_terms.png')
export const ic_version = require('./common/ic_version.png')
export const icon_alert = require('./common/icon_alert.png')
export const icon_calendar = require('./common/icon_calendar.png')
export const icon_checked = require('./common/icon_checked.png')
export const icon_feed = require('./common/icon_feed.png')
export const icon_list = require('./common/icon_list.png')
export const icon_make = require('./common/icon_make.png')
export const icon_myPage = require('./common/icon_myPage.png')
export const icon_unchecked = require('./common/icon_unchecked.png')
export const icon = require('./common/icon.png')
export const profile = require('./common/profile.png')
export const spalash = require('./common/splash.png')


