export const MENU = {
  // 마이페이지
  PROFILE_EDIT: 'PROFILE_EDIT',
  MYPAGE_SETTING: 'MYPAGE_SETTING',
  MYPAGE_FRIEND: 'MYPAGE_FRIEND',
  MYPAGE_ALARM: 'MYPAGE_ALARM',
  MYPAGE_TERMS: 'MYPAGE_TERMS',
  // 빙고
  BINGO_CREATE: 'BINGO_CREATE',
  BINGO_BOARD: 'BINGO_BOARD',
  BINGO_EDIT: 'BINGO_EDIT',
}
