export const MENU = {
  // 마이페이지
  PROFILE_EDIT: 'PROFILE_EDIT',
  MYPAGE_SETTING: 'MYPAGE_SETTING',
  MYPAGE_FRIEND: 'MYPAGE_FRIEND',
  MYPAGE_ALARM: 'MYPAGE_ALARM',
  MYPAGE_TERMS: 'MYPAGE_TERMS',
  MYPAGE_PROFILE: 'MYPAGE_PROFILE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  // 빙고
  BINGO_CREATE: 'BINGO_CREATE',
  BINGO_BOARD: 'BINGO_BOARD',
  BINGO_EDIT: 'BINGO_EDIT',
  //알림
  NOTIFICATION: 'NOTIFICATION',
}
